[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.20"
tungstenite = "0.20"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
enigo = "0.1"
futures-util = "0.3"
warp = {version = "0.3", features = ["tls"]}
